### ISSUE TITLE
connection.connected returns None instead of True in 2.1.0

### ISSUE THREAD

**Issue by scheler** [celery/py-amqp#111]
connection.connected returns None instead of True in release 2.1.0.  Can this be fixed?

```
$ cat foo.py 
from kombu import Connection
connection = Connection('amqp://guest:guest@localhost:5672//')
connection.connect()
print connection.connected
connection.close()


$ pip install -q amqp==1.4.9
$ python foo.py
True
$ pip install -q amqp==2.1.0
$ python foo.py
None

```

**Comment by ask** [comment]
Are you using kombu 3 or kombu 4rc?

Kombu 3 explicitly requires amqp < 2, maybe you have a broken pip version?

You shouldn't depend on Connection.connected for anything, it was actually a mistake to add it there
as I thought it would be possible to verify the connection, but it turns out that is impossible.
