### ISSUE TITLE
KeyError: connection.blocked

### ISSUE THREAD

**Issue by tevansuk** [celery/py-amqp#243]
Hi all.

After the release of 2.4.0, we get "connection.blocked" key errors. This seems to relate to:

Drain events before publish data. (#214)  …
b0bc72f

We use:

celery 4.2.0
kombu 4.2.2.post1

The server is RabbitMQ 3.1.5 (I suspect this is the issue).

Falling back to amqp==2.3.2 fixes the problem for us.

**Comment by clokep** [comment]
Could probably change that code to `client_properties['capabilities'].get('connection.blocked', False)`, which just defaults to not supporting it if the key doesn't exist.

**Comment by matusvalo** [comment]
Yes I think this is possible solution. @thedrow please postpone new release until this is fixed. I can do the fix soon.

**Comment by clokep** [comment]
This also makes me wonder if this package has a documented minimum RabbitMQ version it supports?

**Comment by thedrow** [comment]
We unfortunately don't.

**Comment by clokep** [comment]
I was curious when this feature was added: [Blocked connection notifications](https://www.rabbitmq.com/connection-blocked.html) was added to RabbitMQ 3.2.0 (so one version after @tevansuk's!) released October 23, 2013 (info from [RabbitMQ changelog](https://www.rabbitmq.com/changelog.html)).

Seems easy enough to include a workaround though...

**Comment by matusvalo** [comment]
Hm I am not sure whether it is only supported version of RMQ. There can be uses of this library also with other brokers than RMQ. I think that we should support also brokers not supporting RMQ extensions.

**Comment by matusvalo** [comment]
I have spent some time looking into code responsible for negotiating capabilities with server. I think that there is a room for improvements because:
* `Connection.client_properties['capabilities']` contains only capabilities set to `True`. Basically it is the same as the set of supported capabilities.
* `Connection.client_properties` does not contain `'capabilities'` key when broker does not contain any capability - basically brokers without extensions.
See:
https://github.com/celery/py-amqp/blob/f507172c1fa88e6c6f50e36762876b3116f4715e/amqp/connection.py#L373-L383

So when support of some capability needs to be checked, following code needs to be used:
```python
capabilities = self.connection.client_properties.get('capabilities', {})
if capabilities.get('connection.blocked', False)
```
I think this deserves separate function which should be used instead accessing directly  `Connection.client_properties['capabilities']`

But I think this should be done in separate PR.

**Comment by matusvalo** [comment]
@tevansuk fix of the issue is in master. Could you check whether this issue still occures when you use master?

**Comment by tevansuk** [comment]
Absolutely, I'll take a look in the morning.

**Comment by thedrow** [comment]
Right. @matusvalu are we ready for a bugfix release?
