### ISSUE TITLE
MemoryError establishing a connection to Azure Service Bus

### ISSUE THREAD

**Issue by zmullett** [celery/py-amqp#51]
Not sure if amqp and Azure Service Bus should cooperate, but I receive a MemoryError (originating from transport._AbstractTransport.read_frame). The payload size unpacked from he frame header seems incorrect.

I attempt to establish the connection like so:

connection = amqp.connection.Connection(
	host='MYSERVICENAMESPACE.servicebus.windows.net',
	userid='owner',
	password='MYPASSWORD')

**Comment by amirrustam** [comment]
@ask since Kombu now has a Qpid transport and Qpid supports AMQP 1.0, then would Celery work with Azure Service Bus by using `qpid://` transport?

Do you see any obvious or easily foreseeable issue with this?

I'm going to run a test today to investigate and report back here, but I would appreciate your insights on this matter.

**Comment by FlaPer87** [comment]
@amirrustam I'd recommend having an amqp1.0 specific transport rather than having a single transport for qpidd and all amqp1.0 capable services. It'd be possible to use `qpid-proton` to write a transport for kombu.

I might take a look at this sometime later. Want to file an issue requesting this?

**Comment by amirrustam** [comment]
@FlaPer87 Thanks for the follow up. The way I understand, the [Kombu Qpid transport](http://kombu.readthedocs.org/en/latest/reference/kombu.transport.qpid.html) uses the [Qupid Messaging API ](http://qpid.apache.org/components/messaging-api/index.html) (`qpid-python`) which uses AMQP 1.0 and 0-10. I believe this fulfills your recommendation??

What are the benefits of `proton` over the `messaging` API? Honestly, I'm not clear on their primary differences, so I would appreciate any enlightenment. Though I do know that Microsoft uses Qpid Proton to test Azure Service Bus internally, and it is the officially recommend client library within their documentation. 

I'm writing a little test Django app tonight, so I can submit a more informed issue. I will do so under the Kombu repo.

AMQP 1.0 spec was finalized in 2011, so I'm a bit surprised its support is not very clear within Celery (or maybe I'm missing something!).

**Comment by thedrow** [comment]
AMQP 1.0 is wierd and pretty bad designed as far as I understand.
RabbitMQ uses 0.9.1 which is what's used with Celery the most.
If you feel like adding support for AMQP 1.0 we'd love to have that but we have a lot of other stuff on our plate for now so we can't commit to it at the moment.
Feel free to open a new issue about AMQP 1.0 support.

**Comment by Korijn** [comment]
@amirrustam did you ever get this working?

**Comment by amirrustam** [comment]
@Korijn I ended using RabbitMQ, which does not use AMQP 1.0, on my own servers instead of using Azure Service Bus (requires AMQP 1.0). Though I will pursue this as soon as I get some time, since I would love to have the ability to use a third-party AMQP 1.0 message queues. I'll follow up here for the sake of public documentation.

**Comment by Korijn** [comment]
I've since decided to switch to Redis since it's available as a managed service on Azure as well..
