### ISSUE TITLE
Docs version 'latest' missing changelog entries for 2.x

### ISSUE THREAD

**Issue by edmorley** [celery/py-amqp#97]
Visiting https://amqp.readthedocs.io/ redirects to the `latest` version tag of the docs.

However these don't mention v2.x on the changelog, instead only <= 1.4.9:
https://amqp.readthedocs.io/en/latest/changelog.html
(I've even tried forcing a RTD rebuild using https://readthedocs.org/projects/amqp/builds/)

Strangely the `stable` version does have those changelog entries:
https://amqp.readthedocs.io/en/stable/changelog.html
(Though as #94 notes, the banner there about it being for a development version is incorrect)

It seems as though `latest` and `master` on readthedocs could be combined, and the default version tag be made to be `stable`?

Also the readme mentions both 0.9.1 and 2.0.0rc2, rather than 2.0.1:
https://github.com/celery/py-amqp/blame/b12272c54a88ad428a7eaf837280f136b7252e08/README.rst#L2
https://github.com/celery/py-amqp/blame/b12272c54a88ad428a7eaf837280f136b7252e08/README.rst#L7

Many thanks :-)

**Comment by pquentin** [comment]
There's also a confusion between http://py-amqp.readthedocs.io/en/latest/ and https://amqp.readthedocs.io/en/latest/.

**Comment by ask** [comment]
@edmorley RTD latest is now changed to use the 2.0 branch,
and the README was rendered from source to fix the wrong version.

@pquentin I cannot find references to http://py-amqp.readthedocs.io anywhere?

**Comment by pquentin** [comment]
@ask The situation is quite confusing between all the RabbitMQ/AMQP libraries. The first thing I saw about py-amqp is that it's a "amqplib fork" but I have no idea what amqplib is. (I found it now but the first thing I saw about "amqplib" is a Node.js library.) Maybe it's time to position the library differently: saying what it does well, not what it does differently.

The other issue is that it's the first time I see a project use a different name on RTD and GitHub. This is why I wondered "does py-amqp.readthedocs.io exist ?". It also comes up if you look up "py-amqp readthedocs" on Google Search. I understand that "amqp" is the source of truth since the name on PyPI is the most difficult to change. With such a generic name, confusion is bound to happen, so it would be nice to try to reduce it as much as possible. One option is 1/ changing the name on Github to amqp 2/ removing py-amqp.readthedocs.org.

**Comment by ask** [comment]
@pquentin The purpose of this project is to be generic, but it's created out of the needs of Kombu.    Kombu with py-amqp has very little overhead compared to kombu with "virtual transports", and it implements many patterns that's required for most applications of AMQP, like connection pools, failover, etc.

**Comment by ask** [comment]
The comment on the name is a good point, and we could probably rename the repository.  The reason I named it py-amqp in the first place is I was thinking we may have clients written in languages other than Python some day.

**Comment by eliasdorneles** [comment]
Hello!

The ReadTheDocs setup seems to continue being a problem -- here is an image illustrating my confusion trying to figure out the latest stable version:

![issue-docs-amqp](https://user-images.githubusercontent.com/37565/54918080-9d0bcf00-4efd-11e9-86e9-4395c1fb2dc9.png)

(I wanted to find the changelog, i ended up finding it on Github: https://github.com/celery/py-amqp/blob/master/Changelog)
